# Generated by Django 3.1.4 on 2021-01-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210104_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='days',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
